### ISSUE TITLE
each request return 200。

### ISSUE THREAD

**Issue by mark-wang-sh** [medcl/lua-resty-weedfs#1]
how to return 304？

**Comment by medcl** [comment]
you can use it as upstream,do gzip and cache in your domain config:

**Comment by simonhoo** [comment]
not found 'resty.http':

2016/11/03 18:03:45 [error] 1415#0: *12 lua entry thread aborted: runtime error: /usr/local/openresty/nginx/conf/weedfs.lua:58: module 'resty.http' not found:
    no field package.preload['resty.http']
    no file '/usr/local/openresty/lualib/resty/http.lua'
    no file '/usr/local/openresty/site/lualib/resty/http.lua'
    no file '/usr/local/openresty/site/lualib/resty/http/init.lua'
    no file '/usr/local/openresty/lualib/resty/http.lua'
    no file '/usr/local/openresty/lualib/resty/http/init.lua'
    no file './resty/http.lua'
    no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta2/resty/http.lua'
    no file '/usr/local/share/lua/5.1/resty/http.lua'
    no file '/usr/local/share/lua/5.1/resty/http/init.lua'
    no file '/usr/local/openresty/luajit/share/lua/5.1/resty/http.lua'
    no file '/usr/local/openresty/luajit/share/lua/5.1/resty/http/init.lua'
    no file '/usr/local/openresty/site/lualib/resty/http.so'
    no file '/usr/local/openresty/lualib/resty/http.so'
    no file './resty/http.so'
    no file '/usr/local/lib/lua/5.1/resty/http.so'
    no file '/usr/local/openresty/luajit/lib/lua/5.1/resty/http.so'
    no file '/usr/local/lib/lua/5.1/loadall.so'
    no file '/usr/local/openresty/site/lualib/resty.so'
    no file '/usr/local/openresty/lualib/resty.so'
    no file './resty.so'
    no file '/usr/local/lib/lua/5.1/resty.so'
    no file '/usr/local/openresty/luajit/lib/lua/5.1/resty.so'
    no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
    [C]: in function 'require'
    /usr/local/openresty/nginx/conf/weedfs.lua:58: in function 'save_orig_file'
    /usr/local/openresty/nginx/conf/weedfs.lua:143: in function 'process_img'
    /usr/local/openresty/nginx/conf/weedfs.lua:228: in function </usr/local/openresty/nginx/conf/weedfs.lua:1>, client: 10.50.90.68, server: localhost, request: "GET /img/100x100s/2,037d3eab35.jpg HTTP/1.1", host: "10.50.130.90"

**Comment by medcl** [comment]
@simonhoo 确保配置正确路径     lua_package_path "/usr/local/openresty/lualib/?.lua;;";

**Comment by simonhoo** [comment]
@medcl 
OK, 已经解决：
mv lua-resty-weedfs/resty/*.lua  /usr/local/openresty/lualib/resty/

thank U!
